/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoTenantsRouteImport } from './routes/demo.tenants'
import { Route as DemoStatsRouteImport } from './routes/demo.stats'
import { Route as DemoSettingsRouteImport } from './routes/demo.settings'
import { Route as DemoScheduleRouteImport } from './routes/demo.schedule'
import { Route as DemoRoomsRouteImport } from './routes/demo.rooms'
import { Route as DemoInvoicesRouteImport } from './routes/demo.invoices'
import { Route as DemoDashboardRouteImport } from './routes/demo.dashboard'
import { Route as DemoCommunityRouteImport } from './routes/demo.community'
import { Route as DemoBranchesRouteImport } from './routes/demo.branches'
import { Route as DemoApplicationsRouteImport } from './routes/demo.applications'
import { Route as AuthenticatedTenantsRouteImport } from './routes/_authenticated.tenants'
import { Route as AuthenticatedStatsRouteImport } from './routes/_authenticated.stats'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as AuthenticatedScheduleRouteImport } from './routes/_authenticated.schedule'
import { Route as AuthenticatedRoomsRouteImport } from './routes/_authenticated.rooms'
import { Route as AuthenticatedRoomTypesRouteImport } from './routes/_authenticated.room-types'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated.onboarding'
import { Route as AuthenticatedInvoicesRouteImport } from './routes/_authenticated.invoices'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedCommunityRouteImport } from './routes/_authenticated.community'
import { Route as AuthenticatedBranchesRouteImport } from './routes/_authenticated.branches'
import { Route as AuthenticatedApplicationsRouteImport } from './routes/_authenticated.applications'
import { Route as DemoTenantsTenantIdRouteImport } from './routes/demo.tenants.$tenantId'
import { Route as AuthenticatedTenantsNewRouteImport } from './routes/_authenticated.tenants.new'
import { Route as AuthenticatedTenantsTenantIdRouteImport } from './routes/_authenticated.tenants.$tenantId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTenantsRoute = DemoTenantsRouteImport.update({
  id: '/demo/tenants',
  path: '/demo/tenants',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStatsRoute = DemoStatsRouteImport.update({
  id: '/demo/stats',
  path: '/demo/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoSettingsRoute = DemoSettingsRouteImport.update({
  id: '/demo/settings',
  path: '/demo/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoScheduleRoute = DemoScheduleRouteImport.update({
  id: '/demo/schedule',
  path: '/demo/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoomsRoute = DemoRoomsRouteImport.update({
  id: '/demo/rooms',
  path: '/demo/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoInvoicesRoute = DemoInvoicesRouteImport.update({
  id: '/demo/invoices',
  path: '/demo/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoDashboardRoute = DemoDashboardRouteImport.update({
  id: '/demo/dashboard',
  path: '/demo/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoCommunityRoute = DemoCommunityRouteImport.update({
  id: '/demo/community',
  path: '/demo/community',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoBranchesRoute = DemoBranchesRouteImport.update({
  id: '/demo/branches',
  path: '/demo/branches',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApplicationsRoute = DemoApplicationsRouteImport.update({
  id: '/demo/applications',
  path: '/demo/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTenantsRoute = AuthenticatedTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStatsRoute = AuthenticatedStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedScheduleRoute = AuthenticatedScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRoomsRoute = AuthenticatedRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRoomTypesRoute = AuthenticatedRoomTypesRouteImport.update({
  id: '/room-types',
  path: '/room-types',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInvoicesRoute = AuthenticatedInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCommunityRoute = AuthenticatedCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBranchesRoute = AuthenticatedBranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedApplicationsRoute =
  AuthenticatedApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const DemoTenantsTenantIdRoute = DemoTenantsTenantIdRouteImport.update({
  id: '/$tenantId',
  path: '/$tenantId',
  getParentRoute: () => DemoTenantsRoute,
} as any)
const AuthenticatedTenantsNewRoute = AuthenticatedTenantsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedTenantsRoute,
} as any)
const AuthenticatedTenantsTenantIdRoute =
  AuthenticatedTenantsTenantIdRouteImport.update({
    id: '/$tenantId',
    path: '/$tenantId',
    getParentRoute: () => AuthenticatedTenantsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/applications': typeof AuthenticatedApplicationsRoute
  '/branches': typeof AuthenticatedBranchesRoute
  '/community': typeof AuthenticatedCommunityRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/invoices': typeof AuthenticatedInvoicesRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/room-types': typeof AuthenticatedRoomTypesRoute
  '/rooms': typeof AuthenticatedRoomsRoute
  '/schedule': typeof AuthenticatedScheduleRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/stats': typeof AuthenticatedStatsRoute
  '/tenants': typeof AuthenticatedTenantsRouteWithChildren
  '/demo/applications': typeof DemoApplicationsRoute
  '/demo/branches': typeof DemoBranchesRoute
  '/demo/community': typeof DemoCommunityRoute
  '/demo/dashboard': typeof DemoDashboardRoute
  '/demo/invoices': typeof DemoInvoicesRoute
  '/demo/rooms': typeof DemoRoomsRoute
  '/demo/schedule': typeof DemoScheduleRoute
  '/demo/settings': typeof DemoSettingsRoute
  '/demo/stats': typeof DemoStatsRoute
  '/demo/tenants': typeof DemoTenantsRouteWithChildren
  '/tenants/$tenantId': typeof AuthenticatedTenantsTenantIdRoute
  '/tenants/new': typeof AuthenticatedTenantsNewRoute
  '/demo/tenants/$tenantId': typeof DemoTenantsTenantIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/applications': typeof AuthenticatedApplicationsRoute
  '/branches': typeof AuthenticatedBranchesRoute
  '/community': typeof AuthenticatedCommunityRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/invoices': typeof AuthenticatedInvoicesRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/room-types': typeof AuthenticatedRoomTypesRoute
  '/rooms': typeof AuthenticatedRoomsRoute
  '/schedule': typeof AuthenticatedScheduleRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/stats': typeof AuthenticatedStatsRoute
  '/tenants': typeof AuthenticatedTenantsRouteWithChildren
  '/demo/applications': typeof DemoApplicationsRoute
  '/demo/branches': typeof DemoBranchesRoute
  '/demo/community': typeof DemoCommunityRoute
  '/demo/dashboard': typeof DemoDashboardRoute
  '/demo/invoices': typeof DemoInvoicesRoute
  '/demo/rooms': typeof DemoRoomsRoute
  '/demo/schedule': typeof DemoScheduleRoute
  '/demo/settings': typeof DemoSettingsRoute
  '/demo/stats': typeof DemoStatsRoute
  '/demo/tenants': typeof DemoTenantsRouteWithChildren
  '/tenants/$tenantId': typeof AuthenticatedTenantsTenantIdRoute
  '/tenants/new': typeof AuthenticatedTenantsNewRoute
  '/demo/tenants/$tenantId': typeof DemoTenantsTenantIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authenticated/applications': typeof AuthenticatedApplicationsRoute
  '/_authenticated/branches': typeof AuthenticatedBranchesRoute
  '/_authenticated/community': typeof AuthenticatedCommunityRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/invoices': typeof AuthenticatedInvoicesRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/room-types': typeof AuthenticatedRoomTypesRoute
  '/_authenticated/rooms': typeof AuthenticatedRoomsRoute
  '/_authenticated/schedule': typeof AuthenticatedScheduleRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/stats': typeof AuthenticatedStatsRoute
  '/_authenticated/tenants': typeof AuthenticatedTenantsRouteWithChildren
  '/demo/applications': typeof DemoApplicationsRoute
  '/demo/branches': typeof DemoBranchesRoute
  '/demo/community': typeof DemoCommunityRoute
  '/demo/dashboard': typeof DemoDashboardRoute
  '/demo/invoices': typeof DemoInvoicesRoute
  '/demo/rooms': typeof DemoRoomsRoute
  '/demo/schedule': typeof DemoScheduleRoute
  '/demo/settings': typeof DemoSettingsRoute
  '/demo/stats': typeof DemoStatsRoute
  '/demo/tenants': typeof DemoTenantsRouteWithChildren
  '/_authenticated/tenants/$tenantId': typeof AuthenticatedTenantsTenantIdRoute
  '/_authenticated/tenants/new': typeof AuthenticatedTenantsNewRoute
  '/demo/tenants/$tenantId': typeof DemoTenantsTenantIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/applications'
    | '/branches'
    | '/community'
    | '/dashboard'
    | '/invoices'
    | '/onboarding'
    | '/room-types'
    | '/rooms'
    | '/schedule'
    | '/settings'
    | '/stats'
    | '/tenants'
    | '/demo/applications'
    | '/demo/branches'
    | '/demo/community'
    | '/demo/dashboard'
    | '/demo/invoices'
    | '/demo/rooms'
    | '/demo/schedule'
    | '/demo/settings'
    | '/demo/stats'
    | '/demo/tenants'
    | '/tenants/$tenantId'
    | '/tenants/new'
    | '/demo/tenants/$tenantId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/applications'
    | '/branches'
    | '/community'
    | '/dashboard'
    | '/invoices'
    | '/onboarding'
    | '/room-types'
    | '/rooms'
    | '/schedule'
    | '/settings'
    | '/stats'
    | '/tenants'
    | '/demo/applications'
    | '/demo/branches'
    | '/demo/community'
    | '/demo/dashboard'
    | '/demo/invoices'
    | '/demo/rooms'
    | '/demo/schedule'
    | '/demo/settings'
    | '/demo/stats'
    | '/demo/tenants'
    | '/tenants/$tenantId'
    | '/tenants/new'
    | '/demo/tenants/$tenantId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_authenticated/applications'
    | '/_authenticated/branches'
    | '/_authenticated/community'
    | '/_authenticated/dashboard'
    | '/_authenticated/invoices'
    | '/_authenticated/onboarding'
    | '/_authenticated/room-types'
    | '/_authenticated/rooms'
    | '/_authenticated/schedule'
    | '/_authenticated/settings'
    | '/_authenticated/stats'
    | '/_authenticated/tenants'
    | '/demo/applications'
    | '/demo/branches'
    | '/demo/community'
    | '/demo/dashboard'
    | '/demo/invoices'
    | '/demo/rooms'
    | '/demo/schedule'
    | '/demo/settings'
    | '/demo/stats'
    | '/demo/tenants'
    | '/_authenticated/tenants/$tenantId'
    | '/_authenticated/tenants/new'
    | '/demo/tenants/$tenantId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  DemoApplicationsRoute: typeof DemoApplicationsRoute
  DemoBranchesRoute: typeof DemoBranchesRoute
  DemoCommunityRoute: typeof DemoCommunityRoute
  DemoDashboardRoute: typeof DemoDashboardRoute
  DemoInvoicesRoute: typeof DemoInvoicesRoute
  DemoRoomsRoute: typeof DemoRoomsRoute
  DemoScheduleRoute: typeof DemoScheduleRoute
  DemoSettingsRoute: typeof DemoSettingsRoute
  DemoStatsRoute: typeof DemoStatsRoute
  DemoTenantsRoute: typeof DemoTenantsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tenants': {
      id: '/demo/tenants'
      path: '/demo/tenants'
      fullPath: '/demo/tenants'
      preLoaderRoute: typeof DemoTenantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/stats': {
      id: '/demo/stats'
      path: '/demo/stats'
      fullPath: '/demo/stats'
      preLoaderRoute: typeof DemoStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/settings': {
      id: '/demo/settings'
      path: '/demo/settings'
      fullPath: '/demo/settings'
      preLoaderRoute: typeof DemoSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/schedule': {
      id: '/demo/schedule'
      path: '/demo/schedule'
      fullPath: '/demo/schedule'
      preLoaderRoute: typeof DemoScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/rooms': {
      id: '/demo/rooms'
      path: '/demo/rooms'
      fullPath: '/demo/rooms'
      preLoaderRoute: typeof DemoRoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/invoices': {
      id: '/demo/invoices'
      path: '/demo/invoices'
      fullPath: '/demo/invoices'
      preLoaderRoute: typeof DemoInvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/dashboard': {
      id: '/demo/dashboard'
      path: '/demo/dashboard'
      fullPath: '/demo/dashboard'
      preLoaderRoute: typeof DemoDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/community': {
      id: '/demo/community'
      path: '/demo/community'
      fullPath: '/demo/community'
      preLoaderRoute: typeof DemoCommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/branches': {
      id: '/demo/branches'
      path: '/demo/branches'
      fullPath: '/demo/branches'
      preLoaderRoute: typeof DemoBranchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/applications': {
      id: '/demo/applications'
      path: '/demo/applications'
      fullPath: '/demo/applications'
      preLoaderRoute: typeof DemoApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tenants': {
      id: '/_authenticated/tenants'
      path: '/tenants'
      fullPath: '/tenants'
      preLoaderRoute: typeof AuthenticatedTenantsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/stats': {
      id: '/_authenticated/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof AuthenticatedStatsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/schedule': {
      id: '/_authenticated/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AuthenticatedScheduleRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rooms': {
      id: '/_authenticated/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof AuthenticatedRoomsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/room-types': {
      id: '/_authenticated/room-types'
      path: '/room-types'
      fullPath: '/room-types'
      preLoaderRoute: typeof AuthenticatedRoomTypesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/invoices': {
      id: '/_authenticated/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AuthenticatedInvoicesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/community': {
      id: '/_authenticated/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof AuthenticatedCommunityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/branches': {
      id: '/_authenticated/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof AuthenticatedBranchesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/applications': {
      id: '/_authenticated/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof AuthenticatedApplicationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/demo/tenants/$tenantId': {
      id: '/demo/tenants/$tenantId'
      path: '/$tenantId'
      fullPath: '/demo/tenants/$tenantId'
      preLoaderRoute: typeof DemoTenantsTenantIdRouteImport
      parentRoute: typeof DemoTenantsRoute
    }
    '/_authenticated/tenants/new': {
      id: '/_authenticated/tenants/new'
      path: '/new'
      fullPath: '/tenants/new'
      preLoaderRoute: typeof AuthenticatedTenantsNewRouteImport
      parentRoute: typeof AuthenticatedTenantsRoute
    }
    '/_authenticated/tenants/$tenantId': {
      id: '/_authenticated/tenants/$tenantId'
      path: '/$tenantId'
      fullPath: '/tenants/$tenantId'
      preLoaderRoute: typeof AuthenticatedTenantsTenantIdRouteImport
      parentRoute: typeof AuthenticatedTenantsRoute
    }
  }
}

interface AuthenticatedTenantsRouteChildren {
  AuthenticatedTenantsTenantIdRoute: typeof AuthenticatedTenantsTenantIdRoute
  AuthenticatedTenantsNewRoute: typeof AuthenticatedTenantsNewRoute
}

const AuthenticatedTenantsRouteChildren: AuthenticatedTenantsRouteChildren = {
  AuthenticatedTenantsTenantIdRoute: AuthenticatedTenantsTenantIdRoute,
  AuthenticatedTenantsNewRoute: AuthenticatedTenantsNewRoute,
}

const AuthenticatedTenantsRouteWithChildren =
  AuthenticatedTenantsRoute._addFileChildren(AuthenticatedTenantsRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedApplicationsRoute: typeof AuthenticatedApplicationsRoute
  AuthenticatedBranchesRoute: typeof AuthenticatedBranchesRoute
  AuthenticatedCommunityRoute: typeof AuthenticatedCommunityRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInvoicesRoute: typeof AuthenticatedInvoicesRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedRoomTypesRoute: typeof AuthenticatedRoomTypesRoute
  AuthenticatedRoomsRoute: typeof AuthenticatedRoomsRoute
  AuthenticatedScheduleRoute: typeof AuthenticatedScheduleRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStatsRoute: typeof AuthenticatedStatsRoute
  AuthenticatedTenantsRoute: typeof AuthenticatedTenantsRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedApplicationsRoute: AuthenticatedApplicationsRoute,
  AuthenticatedBranchesRoute: AuthenticatedBranchesRoute,
  AuthenticatedCommunityRoute: AuthenticatedCommunityRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInvoicesRoute: AuthenticatedInvoicesRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedRoomTypesRoute: AuthenticatedRoomTypesRoute,
  AuthenticatedRoomsRoute: AuthenticatedRoomsRoute,
  AuthenticatedScheduleRoute: AuthenticatedScheduleRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStatsRoute: AuthenticatedStatsRoute,
  AuthenticatedTenantsRoute: AuthenticatedTenantsRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface DemoTenantsRouteChildren {
  DemoTenantsTenantIdRoute: typeof DemoTenantsTenantIdRoute
}

const DemoTenantsRouteChildren: DemoTenantsRouteChildren = {
  DemoTenantsTenantIdRoute: DemoTenantsTenantIdRoute,
}

const DemoTenantsRouteWithChildren = DemoTenantsRoute._addFileChildren(
  DemoTenantsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  DemoApplicationsRoute: DemoApplicationsRoute,
  DemoBranchesRoute: DemoBranchesRoute,
  DemoCommunityRoute: DemoCommunityRoute,
  DemoDashboardRoute: DemoDashboardRoute,
  DemoInvoicesRoute: DemoInvoicesRoute,
  DemoRoomsRoute: DemoRoomsRoute,
  DemoScheduleRoute: DemoScheduleRoute,
  DemoSettingsRoute: DemoSettingsRoute,
  DemoStatsRoute: DemoStatsRoute,
  DemoTenantsRoute: DemoTenantsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
